/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iris;

import CSVIO.CSVWriter;
import NeuralNetwork.FeedForwardNeuralNetwork;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DAN
 */
public class Antarmuka extends javax.swing.JFrame {
        private int INPUT_NEURON = 4;
        private int HIDDEN_NEURON = 7;
        private int OUTPUT_NEURON = 3;
        private double[][] bobotIH = new double[INPUT_NEURON][HIDDEN_NEURON];
        private double[][] bobotHO = new double[HIDDEN_NEURON][OUTPUT_NEURON];
        private double[] bobotBiasIH = new double[HIDDEN_NEURON];
        private double[] bobotBiasHO = new double[OUTPUT_NEURON];
        public static int index;
        
        //getter & setter

    public void setBobotIH(double[][] bobotIH) {
        this.bobotIH = bobotIH;
    }

    public void setBobotHO(double[][] bobotHO) {
        this.bobotHO = bobotHO;
    }

    public void setBobotBiasIH(double[] bobotBiasIH) {
        this.bobotBiasIH = bobotBiasIH;
    }

    public void setBobotBiasHO(double[] bobotBiasHO) {
        this.bobotBiasHO = bobotBiasHO;
    }
        
        
    /**
     * Creates new form Antarmuka
     */
    public Antarmuka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        btnTraining = new javax.swing.JButton();
        btnAkurasiTesting = new javax.swing.JButton();
        btnSimpanBobot = new javax.swing.JButton();
        btnAkurasiTraining = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Masukkan Lokasi File Training");

        jLabel2.setText("Lokasi File Testing");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnTraining.setText("Latih Dengan Data Training");
        btnTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrainingActionPerformed(evt);
            }
        });

        btnAkurasiTesting.setText("Uji Akurasi Dengan Data Testing");
        btnAkurasiTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAkurasiTestingActionPerformed(evt);
            }
        });

        btnSimpanBobot.setText("Simpan Bobot");
        btnSimpanBobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanBobotActionPerformed(evt);
            }
        });

        btnAkurasiTraining.setText("Uji dengan data training");
        btnAkurasiTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAkurasiTrainingActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTraining)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAkurasiTesting))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(jTextField2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAkurasiTraining, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(btnSimpanBobot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpanBobot, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAkurasiTesting, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAkurasiTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrainingActionPerformed
        // TODO add your handling code here:
        //E:\MACHINE LEARNING\Iris dataset training.csv
        CSVReader csvReader = new CSVReader();
        csvReader.bacaFileTrainingCSV(jTextField1.getText(), "training");   
             
        jTextArea1.append("File Pelatihan telah dimasukkan kedalam sistem");
    }//GEN-LAST:event_btnTrainingActionPerformed

    private void btnAkurasiTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkurasiTestingActionPerformed
        // TODO add your handling code here:
        CSVReader csvReader = new CSVReader();
        csvReader.bacaFileTrainingCSV(jTextField2.getText(), "testing");
        
    }//GEN-LAST:event_btnAkurasiTestingActionPerformed

    private void btnSimpanBobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanBobotActionPerformed
        //get bobot, kemudian simpan dalam file CSV       
        CSVReader csvReader = new CSVReader();
        bobotBiasIH = csvReader.bacaFileBobotBias("E:\\MACHINE LEARNING\\bobotBiasIH.csv");
        bobotBiasHO = csvReader.bacaFileBobotBias("E:\\MACHINE LEARNING\\bobotBiasHO.csv");
        
        bobotIH = csvReader.bacaFileBobot2D(
                                "E:\\MACHINE LEARNING\\bobotIH.csv", 
                                INPUT_NEURON, 
                                HIDDEN_NEURON
                            );
        
        bobotHO = csvReader.bacaFileBobot2D(
                                "E:\\MACHINE LEARNING\\bobotHO.csv", 
                                HIDDEN_NEURON, 
                                OUTPUT_NEURON
                            );

/*
        System.out.println("BOBOT BIAS INPUT-> HIDDEN");        
        for (int i = 0; i < bobotBiasIH.length; i++) {
            System.out.println(i+" \t"+bobotBiasIH[i]);
        }

        System.out.println("INPUT -> HIDDEN ");
        for (int i = 0; i < INPUT_NEURON; i++) {
            for (int h = 0; h < HIDDEN_NEURON; h++) {
                System.out.print(bobotIH[i][h]+" \t");
            }
            System.out.println("");
        }
        
        System.out.println("HIDDEN -> OUTPUT");
        for (int h = 0; h < HIDDEN_NEURON; h++) {
            for (int o = 0; o < OUTPUT_NEURON; o++) {
                System.out.print(bobotHO[h][o]+" \t");
            }
            System.out.println("");            
        }
*/
        jTextArea1.append("\nBobot telah berhasil disimpan!");
    }//GEN-LAST:event_btnSimpanBobotActionPerformed

    private void btnAkurasiTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkurasiTrainingActionPerformed
        // TODO add your handling code here:
        CSVReader csvRead = new CSVReader();
        
        csvRead.setBobotIH(bobotIH);
        csvRead.setBobotHO(bobotHO);
        csvRead.setBobotBiasIH(bobotBiasIH);
        csvRead.setBobotBiasHO(bobotBiasHO);
        csvRead.bacaFileTrainingCSV(jTextField1.getText(), "testing");

    }//GEN-LAST:event_btnAkurasiTrainingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.append(String.valueOf(index));
        
        //buat array dLatih       
        
        for (int i = 0; i < index; i++) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Antarmuka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Antarmuka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Antarmuka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Antarmuka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Antarmuka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAkurasiTesting;
    private javax.swing.JButton btnAkurasiTraining;
    private javax.swing.JButton btnSimpanBobot;
    private javax.swing.JButton btnTraining;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
